### ISSUE TITLE
Arz - getIsolatedCollateralValue() is not using the up-to-date exchange rate

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-07-blueberry-judging#16]
Arz

medium

# getIsolatedCollateralValue() is not using the up-to-date exchange rate
## Summary

BlueBerryBank.sol:: getIsolatedCollateralValue() is using a wrong exchange rate which doesnt accrue interest before the value is returned so it will return not the most recent value. Because of that a user can get liquidated even if his position is still healthy.

## Vulnerability Detail

getIsolatedCollateralValue() is used in isLiquidatable() when calculating if a given position can be liquidated based on its risk ratio. This function computes the USD value of the isolated collateral for a given position.  

However the problem is that interest is not accrued before the Compounds exchange rate is returned. The correct function to call is exchangeRateCurrent() which first accrues interest and then returns the stored exchange rate. 

getIsolatedCollateralValue() is not a view function so exchangeRateCurrent() can and should be used here. 

## Impact

The user will be unable to call execute() where isLiquidatable() is used but more importantly he could get liquidated even if his position is still healthy

## Code Snippet

https://github.com/sherlock-audit/2023-07-blueberry/blob/7c7e1c4a8f3012d1afd2e598b656010bb9127836/blueberry-core/contracts/BlueBerryBank.sol#L482-L493

```solidity
482: /// @notice Ensure to call `accrue` beforehand to get the most recent value.
483: /// @param positionId ID of the position to compute the isolated collateral value for.
484: /// @return icollValue USD value of the isolated collateral.
485: function getIsolatedCollateralValue(
486:     uint256 positionId
487: ) public override returns (uint256 icollValue) {
488:     Position memory pos = positions[positionId];
489:     /// NOTE: exchangeRateStored has 18 decimals.
490:     uint256 underlyingAmount;
491:     if (_isSoftVault(pos.underlyingToken)) {
492:         underlyingAmount =
493:             (ICErc20(banks[pos.debtToken].bToken).exchangeRateStored() *


```

As you can see exchangeRateStored() is used and the comment above says that accrue should be called but exchangeRateStored() does not accrue interest. This is not a view function so exchangeRateCurrent() should be used.

## Tool used

Manual Review

## Recommendation

Use exchangeRateCurrent() so that interest is accrued before the exchange rate is returned.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Referring to @Gornutz comment, this was marked as No Fix in previous contest and according to sherlock's [rule here](https://docs.sherlock.xyz/audits/judging/judging) should be invalid :
> > In an update contest, issues from the previous contest with wont fix labels are not considered valid.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Shogoki** [comment]
> Escalate
> 
> Referring to @Gornutz comment, this was marked as No Fix in previous contest and according to sherlock's [rule here](https://docs.sherlock.xyz/audits/judging/judging) should be invalid :
> 
> > In an update contest, issues from the previous contest with wont fix labels are not considered valid.

In this case i do not agree. Because the code is different, than in the previous contest. More specificially the difference is that `getIsolatedCollateralValue` is not a view function here, which was the reasoning for the `Wont fix` in the previous contest.

**Comment by nevillehuang** [comment]
> > Escalate
> > Referring to @Gornutz comment, this was marked as No Fix in previous contest and according to sherlock's [rule here](https://docs.sherlock.xyz/audits/judging/judging) should be invalid :
> > > In an update contest, issues from the previous contest with wont fix labels are not considered valid.
> 
> In this case i do not agree. Because the code is different, than in the previous contest. More specificially the difference is that `getIsolatedCollateralValue` is not a view function here, which was the reasoning for the `Wont fix` in the previous contest.

Ok makes sense, but sponsor acknowledged and did not fix and having it as view function or not does not make any difference in code logic compared to the previous contest. So not sure which direction it should go, could go either way, where it could be invalid conforming to sherlock's rules stated above. Will let @hrishibhat decide.

**Comment by securitygrid** [comment]
> More specificially the difference is that getIsolatedCollateralValue is not a view function here

`getIsolatedCollateralValue` removes the `view`, because it calls [oracle.getTokenValue](https://github.com/sherlock-audit/2023-07-blueberry/blob/7c7e1c4a8f3012d1afd2e598b656010bb9127836/blueberry-core/contracts/BlueBerryBank.sol#L499) where the storage needs to be modified to detect the reentry of curvePool/Balancer.

**Comment by 0xArz** [comment]
I agree with @Shogoki  here:

> In this case i do not agree. Because the code is different, than in the previous contest. More specificially the difference is that `getIsolatedCollateralValue` is not a view function here, which was the reasoning for the `Wont fix` in the previous contest.


Its true that this was discussed in the previous contest but as i mentioned in my report and as Shogoki pointed out, in the previous contest `getIsolatedCollateralValue()` was a view function so `exchangeRateCurrent()` could not be used there and that was the reason for the wont fix.

Now that the function is not a view function, i really dont see a reason why `exchangeRateCurrent()` should not be used. One could argue that this is because of gas, but in a function like liquidate using the current exchange rate is genuinely important.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Considering this issue a low severity since this issue was previously identified as a valid issue and rewarded in the previous contest and marked as `Wont Fix` and the Sponsor has acknowledged this issue.
Hence from this contest point of view, this will not be rewarded again.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [nevillehuang](https://github.com/sherlock-audit/2023-07-blueberry-judging/issues/16/#issuecomment-1693506198): accepted
