### ISSUE TITLE
B353N - Lack of Withdraw Mechanism in CurveStableOracle.sol and Potential Funds Lockup

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-07-blueberry-judging#2]
B353N

medium

# Lack of Withdraw Mechanism in CurveStableOracle.sol and Potential Funds Lockup
## Summary

The purpose of this report is to highlight a critical issue within the smart contract CurveStableOracle.sol. The contract contains a potential vulnerability that can lead to the permanent lockup of user funds. This vulnerability arises due to the absence of a withdraw mechanism, combined with the presence of an external payable fallback function (receive()). As a result, if users accidentally send Ether to this contract, the funds may become inaccessible, leading to a loss of assets.

## Code 
https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/oracle/CurveStableOracle.sol#L72-L73

## Impact

As a result of this vulnerability, users who accidentally send Ether to the CurveStableOracle.sol contract will face the risk of permanent loss. Since the contract does not include any code to facilitate the return of Ether to the sender, the funds will remain locked within the contract indefinitely. This can have significant financial implications for users who unknowingly fall victim to this issue.

## Mitingation

To mitigate the risks associated with this vulnerability and ensure the safety of user funds, the following actions are recommended:

Bacause this contract not suppouse to receive ETH you can just remove this function 
Or
Implement a Withdraw Mechanism: Introduce a mechanism within the contract that allows users  or owners to withdraw Ether that has been mistakenly sent to the contract. This could involve creating a dedicated function that transfers the Ether back to the sender.

**Comment by B353N** [comment]
Escalate
As we can see here https://github.com/crytic/slither/wiki/Detector-Documentation#contracts-that-lock-ether 
`Contract with a payable function, but without a withdrawal capacity.` is issue with `Severity: Medium`
So i think this is valid issue this contract have payable function to receive ETH but no have withdraw mechanism. So as impack user or protocol ETH can be locked in contract forever!

**Comment by sherlock-admin2** [comment]
> Escalate
> As we can see here https://github.com/crytic/slither/wiki/Detector-Documentation#contracts-that-lock-ether or here https://secureum.substack.com/p/security-pitfalls-and-best-practices-101
> `Contract with a payable function, but without a withdrawal capacity.` is issue with `Severity: Medium`
> So i think this is valid issue this contract have payable function to receive ETH but no have withdraw mechanism. So as impack user or protocol ETH can be locked in contract forever!

    You've deleted an escalation for this issue.
