### ISSUE TITLE
cryptoThemeX - Wrong precision in ChainlinkAdapterOracleL2.getPrice function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-07-blueberry-judging#55]
cryptoThemeX

high

# Wrong precision in ChainlinkAdapterOracleL2.getPrice function
## Summary
`ChainlinkAdapterOracleL2.getPrice(address token_)` function computes and returns USD price of the specified token with a fixed/ hardcoded precision of 8 decimal. However, certain tokens in chainlink price feed have different decimal precision. This results in wrong calculation of token price in USD.

## Vulnerability Detail
https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/oracle/ChainlinkAdapterOracleL2.sol#L105-L147

In line 144-146, `Constants.CHAINLINK_PRICE_FEED_PRECISION` is used as precision factor for Chainlink price feed values. The `BlueBerryConst.sol` file sets its value to 8 i.e `CHAINLINK_PRICE_FEED_PRECISION = 1e8`.

However, there exist tokens which has USD price precision higher than 8 decimals, such as `AMPL / USD` pair has [price precision of 18 decimals](https://docs.chain.link/data-feeds/price-feeds/addresses) ([contract link](https://etherscan.io/address/0xe20CA8D7546932360e37E9D72c1a47334af57706#readContract#F3))

Moreover, chainlink web states [Each feed uses a different number of decimal places for answers](https://docs.chain.link/data-feeds/using-data-feeds#:~:text=Each%20feed%20uses%20a%20different%20number%20of%20decimal%20places%20for%20answers). Therefore, fixed 8 decimal precision cannot be used for each token.

## Impact
1. Wrong calculation of token price in USD.
2. Makes the project inconsistent.
3. Funds may lost as user may withdraw more OR deposit lesser than required.

## Code Snippet
https://github.com/sherlock-audit/2023-07-blueberry/blob/main/blueberry-core/contracts/oracle/ChainlinkAdapterOracleL2.sol#L105-L147

## Tool used
VS Code and Manual Review

## Recommendation
Store the decimals for each token or fetch it from price feed. 

## Reference
1. https://github.com/sherlock-audit/2022-08-sentiment-judging/blob/main/019-H/1-report.md
2. https://github.com/Cyfrin/2023-07-foundry-defi-stablecoin/issues/1028

Duplicate of #133

**Comment by cryptothemex** [comment]
What if a token has been whitelisted and being used by  protocol with hardcoded precision of 8 deicmals. Later, chainlink updates the token's price precision to 18 or someother ratio, the protocol admin has no way to update the protocol and protocol will compute prices with wrong precision. That's why chainlink explicitly provides decimals() function and protocol should make use of it instead of using harcoded precision if protocol plans to work right for longer term.
